# Generated by Django 3.2.7 on 2022-02-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211214_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(blank=True, choices=[('PE', 'People'), ('PL', 'Places'), ('MM', 'Mystical Moments'), ('NA', 'Nature')], max_length=2, null=True),
        ),
    ]
