# Generated by Django 3.2.7 on 2021-11-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_meditation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meditation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meditation',
            name='source',
            field=models.URLField(blank=True),
        ),
    ]
