# Generated by Django 3.2.7 on 2022-02-13 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_mainpageslideshowphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SI', 'Slideshow'), ('MI', 'Menu')], max_length=2)),
                ('order', models.PositiveIntegerField()),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.photo')),
            ],
        ),
        migrations.DeleteModel(
            name='MainPageSlideshowPhoto',
        ),
    ]
