# Generated by Django 3.2.7 on 2021-11-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20211118_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=200, unique=True)),
                ('role', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
