# Generated by Django 3.2.7 on 2022-02-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_mainpagephoto_hyperlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagephoto',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
