# Generated by Django 3.2.7 on 2021-11-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_mainpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hometext',
            old_name='text',
            new_name='content',
        ),
    ]
