# Generated by Django 3.2.7 on 2021-11-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_text_hometext_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainPage',
            new_name='MainPageFrag',
        ),
        migrations.DeleteModel(
            name='HomeText',
        ),
    ]
