# Generated by Django 3.2.7 on 2021-11-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20211119_1242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainPageFrag',
            new_name='MainPageFragment',
        ),
    ]
