# Generated by Django 3.2.7 on 2022-02-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_mainpagephoto_hyperlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagephoto',
            name='hyperlink',
            field=models.CharField(blank=True, choices=[('SD', 'spiritual_direction'), ('BL', 'blog'), ('GM', 'guided_meditations'), ('MY', 'ministry'), ('SJ', 'sacred_journeys'), ('AM', 'art_and_music')], max_length=2, null=True),
        ),
    ]
