# Generated by Django 3.2.7 on 2021-11-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_mainpagefrag_mainpagefragment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20, unique=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.AlterField(
            model_name='meditation',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
