# Generated by Django 3.2.7 on 2022-03-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_mainpagephoto_hyperlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_file', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(blank=True, choices=[('PE', 'People'), ('PL', 'Places'), ('MM', 'Mystical Moments'), ('NA', 'Nature')], max_length=2, null=True)),
                ('source', models.URLField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
