# Generated by Django 3.2.7 on 2022-03-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_testphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SacredJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('destination', models.CharField(max_length=50)),
                ('banner_picture', models.URLField(blank=True, null=True)),
                ('worldwidequest_link', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('itinerary', models.TextField(blank=True, null=True)),
                ('tour_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('group_size', models.IntegerField(blank=True, null=True)),
                ('map_image', models.URLField(blank=True, null=True)),
                ('included_features', models.TextField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='TestPhoto',
        ),
    ]
