# Generated by Django 3.2.7 on 2022-03-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20220323_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sacredjourney',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='sacredjourney',
            name='slug',
            field=models.SlugField(default='a-mindful-journey-to-tuscany', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
