# Generated by Django 3.2.7 on 2022-04-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_ministerialrecordtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministerialrecordtest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
