# Generated by Django 3.2.7 on 2022-04-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_ministerialrecordtest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinisterialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, null=True)),
                ('middle_initial', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('mailing_address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state_prov', models.TextField(blank=True, null=True)),
                ('postal_zip', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('phone_home', models.TextField(blank=True, null=True)),
                ('phone_office', models.TextField(blank=True, null=True)),
                ('phone_mobile', models.TextField(blank=True, null=True)),
                ('present_position', models.TextField(blank=True, null=True)),
                ('present_position_startdate', models.DateField(blank=True, null=True)),
                ('preliminary_uu_fellowship_startdate', models.DateField(blank=True, null=True)),
                ('why_are_you_seeking_a_ministry_now', models.TextField(blank=True, null=True)),
                ('describe_the_new_ministry_you_hope_for', models.TextField(blank=True, null=True)),
                ('awards_and_honors', models.TextField(blank=True, null=True)),
                ('published_writings', models.TextField(blank=True, null=True)),
                ('personal_and_family_situation', models.TextField(blank=True, null=True)),
                ('background_and_development', models.TextField(blank=True, null=True)),
                ('denominational_and_community_activities', models.TextField(blank=True, null=True)),
                ('nonprofessional_interests', models.TextField(blank=True, null=True)),
                ('ministerial_development', models.TextField(blank=True, null=True)),
                ('ministerial_roles_and_functions', models.TextField(blank=True, null=True)),
                ('ministerial_skills_and_current_special_interests', models.TextField(blank=True, null=True)),
                ('approach_to_religious_education', models.TextField(blank=True, null=True)),
                ('role_of_music_and_arts', models.TextField(blank=True, null=True)),
                ('involvement_in_stewardship', models.TextField(blank=True, null=True)),
                ('theological_orientation', models.TextField(blank=True, null=True)),
                ('preaching_worship', models.TextField(blank=True, null=True)),
                ('pastoral_care', models.TextField(blank=True, null=True)),
                ('spiritual_life', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MinisterialRecordImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_file', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('PW', 'PW'), ('PC', 'PC'), ('SL', 'SL'), ('CC', 'CC'), ('RE', 'RE'), ('AD', 'AD')], max_length=2)),
                ('source', models.URLField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.DeleteModel(
            name='MinisterialRecordTest',
        ),
    ]
