# Generated by Django 3.2.7 on 2022-04-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20220406_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministerialrecord',
            name='mailing_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
