# Generated by Django 3.2.7 on 2022-04-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_ministerialrecord_mailing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministerialrecord',
            name='administration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ministerialrecord',
            name='community_connection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ministerialrecord',
            name='religious_education',
            field=models.TextField(blank=True, null=True),
        ),
    ]
