# Generated by Django 3.2.7 on 2022-04-06 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20220406_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministerialrecordimage',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)]),
        ),
    ]
