# Generated by Django 3.2.7 on 2022-04-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=20, null=True)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('video_caption', models.TextField(blank=True, null=True)),
                ('other_text', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.DeleteModel(
            name='MinistryFragment',
        ),
    ]
