# Generated by Django 3.2.7 on 2022-04-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_auto_20220426_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministrypage',
            name='heading',
            field=models.CharField(default='Ministry', max_length=20),
        ),
    ]
