# Generated by Django 3.2.7 on 2022-04-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_alter_ministrypage_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministerialrecord',
            name='administration_image',
            field=models.FileField(blank=True, null=True, upload_to='media/ministerial-record-images/'),
        ),
        migrations.AddField(
            model_name='ministerialrecord',
            name='community_connection_image',
            field=models.FileField(blank=True, null=True, upload_to='media/ministerial-record-images/'),
        ),
        migrations.AddField(
            model_name='ministerialrecord',
            name='pastoral_care_image',
            field=models.FileField(blank=True, null=True, upload_to='media/ministerial-record-images/'),
        ),
        migrations.AddField(
            model_name='ministerialrecord',
            name='preaching_worship_image',
            field=models.FileField(blank=True, null=True, upload_to='media/ministerial-record-images/'),
        ),
        migrations.AddField(
            model_name='ministerialrecord',
            name='religious_education_image',
            field=models.FileField(blank=True, null=True, upload_to='media/ministerial-record-images/'),
        ),
        migrations.AddField(
            model_name='ministerialrecord',
            name='spiritual_life_image',
            field=models.FileField(blank=True, null=True, upload_to='media/ministerial-record-images/'),
        ),
    ]
