# Generated by Django 3.2.7 on 2022-05-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_auto_20220427_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiritualDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Spiritual Direction', max_length=20, null=True)),
                ('what_is_spiritual_direction_image', models.FileField(blank=True, null=True, upload_to='media/spiritual-direction-images/')),
                ('what_do_spiritual_directors_do_image', models.FileField(blank=True, null=True, upload_to='media/spiritual-direction-images/')),
                ('one_to_one_sessions_image', models.FileField(blank=True, null=True, upload_to='media/spiritual-direction-images/')),
                ('contact_wayne_for_a_session_image', models.FileField(blank=True, null=True, upload_to='media/spiritual-direction-images/')),
                ('what_is_spiritual_direction', models.TextField(blank=True, null=True)),
                ('what_do_spiritual_directors_do', models.TextField(blank=True, null=True)),
                ('one_to_one_sessions', models.TextField(blank=True, null=True)),
                ('contact_wayne_for_a_session', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MinisterialRecordImage',
        ),
    ]
