# Generated by Django 3.2.7 on 2022-05-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_auto_20220504_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spiritualdirection',
            old_name='one_to_one_sessions',
            new_name='one_on_one_sessions',
        ),
        migrations.RenameField(
            model_name='spiritualdirection',
            old_name='one_to_one_sessions_image',
            new_name='one_on_one_sessions_image',
        ),
    ]
