# Generated by Django 3.2.7 on 2022-05-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_auto_20220504_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_source',
        ),
    ]
