# Generated by Django 3.2.7 on 2022-05-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_remove_post_image_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacredjourney',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
