# Generated by Django 3.2.7 on 2022-05-06 19:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_mainpage_slideimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideimage',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slideimage',
            name='image',
            field=models.FileField(default=datetime.datetime(2022, 5, 6, 19, 30, 11, 289913, tzinfo=utc), upload_to='media/slideshow/'),
            preserve_default=False,
        ),
    ]
