# Generated by Django 3.2.7 on 2022-05-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_auto_20220509_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='tagline',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
