# Generated by Django 3.2.7 on 2022-05-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_mainpage_tagline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainPageFragment',
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='tagline',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.DeleteModel(
            name='MainPagePhoto',
        ),
    ]
