# Generated by Django 3.2.7 on 2022-05-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_auto_20220509_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministerialrecord',
            name='record_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
