# Generated by Django 3.2.7 on 2022-05-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_ministerialrecord_record_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidedMeditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('audio_file', models.FileField(upload_to='media/meditations/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.RemoveField(
            model_name='meditation',
            name='status',
        ),
        migrations.AddField(
            model_name='meditation',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='media/meditations/'),
        ),
    ]
