# Generated by Django 3.2.7 on 2022-05-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0039_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='tagline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
