# Generated by Django 3.2.7 on 2022-05-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0041_alter_spiritualdirection_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidedMeditationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('main_text', models.TextField(blank=True, null=True)),
                ('main_image', models.FileField(blank=True, null=True, upload_to='media/meditations/')),
            ],
        ),
    ]
