# Generated by Django 3.2.7 on 2022-05-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0042_guidedmeditationpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_style', models.TextField(blank=True, null=True)),
                ('font_color', models.CharField(blank=True, max_length=200, null=True)),
                ('background_color', models.CharField(blank=True, max_length=200, null=True)),
                ('font_family', models.CharField(blank=True, max_length=200, null=True)),
                ('font_weight', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
