# Generated by Django 3.2.7 on 2022-05-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0043_stylecontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiritualdirection',
            name='blurb',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
