# Generated by Django 3.2.7 on 2022-05-27 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0045_galleryimage_capition_font_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='capition_font_size',
            new_name='caption_font_size',
        ),
    ]
