# Generated by Django 3.2.7 on 2022-05-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0046_rename_capition_font_size_galleryimage_caption_font_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='caption_font_size',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='font_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
