# Generated by Django 3.2.7 on 2022-05-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0047_auto_20220527_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylecontrol',
            name='font_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stylecontrol',
            name='header_maintext_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stylecontrol',
            name='header_maintext_font_family',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stylecontrol',
            name='header_maintext_font_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stylecontrol',
            name='header_smalltext_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stylecontrol',
            name='header_smalltext_font_family',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stylecontrol',
            name='header_smalltext_font_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
