# Generated by Django 3.2.7 on 2022-06-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0051_alter_stylecontrol_font_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylecontrol',
            name='font_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='stylecontrol',
            name='header_maintext_font_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='stylecontrol',
            name='header_smalltext_font_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
