# Generated by Django 3.2.7 on 2022-06-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0052_auto_20220601_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylecontrol',
            name='header_maintext_font_size',
        ),
        migrations.RemoveField(
            model_name='stylecontrol',
            name='header_smalltext_font_size',
        ),
        migrations.AlterField(
            model_name='stylecontrol',
            name='font_family',
            field=models.CharField(blank=True, choices=[('FU', 'Futura'), ('GA', 'Garamond'), ('HE', 'Helvetica'), ('PA', 'Papyrus'), ('RO', 'Rockwell'), ('SO', 'Source Sans Pro'), ('TN', 'Times New Roman'), ('VE', 'Verdana')], default='SO', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stylecontrol',
            name='font_size',
            field=models.DecimalField(blank=True, decimal_places=1, default=18, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='stylecontrol',
            name='header_maintext_font_family',
            field=models.CharField(blank=True, choices=[('FU', 'Futura'), ('GA', 'Garamond'), ('HE', 'Helvetica'), ('PA', 'Papyrus'), ('RO', 'Rockwell'), ('SO', 'Source Sans Pro'), ('TN', 'Times New Roman'), ('VE', 'Verdana')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stylecontrol',
            name='header_smalltext_font_family',
            field=models.CharField(blank=True, choices=[('FU', 'Futura'), ('GA', 'Garamond'), ('HE', 'Helvetica'), ('PA', 'Papyrus'), ('RO', 'Rockwell'), ('SO', 'Source Sans Pro'), ('TN', 'Times New Roman'), ('VE', 'Verdana')], max_length=200, null=True),
        ),
    ]
