# Generated by Django 3.2.7 on 2022-06-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0053_auto_20220601_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='font_size',
            field=models.DecimalField(blank=True, decimal_places=1, default=18, max_digits=3, null=True),
        ),
    ]
