# Generated by Django 3.2.7 on 2022-07-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0055_auto_20220702_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='SacredJourneyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upcoming_journey_heading', models.CharField(default='Upcoming Journeys', max_length=20)),
                ('previous_journey_heading', models.CharField(default='Previous Journeys', max_length=20)),
            ],
        ),
    ]
