# Generated by Django 3.2.7 on 2022-07-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0056_sacredjourneypage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sacredjourneypage',
            old_name='previous_journey_heading',
            new_name='previous_journeys_heading',
        ),
        migrations.RenameField(
            model_name='sacredjourneypage',
            old_name='upcoming_journey_heading',
            new_name='upcoming_journeys_heading',
        ),
    ]
