# Generated by Django 3.2.7 on 2022-07-13 22:52

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0058_auto_20220713_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylecontrol',
            name='font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
