# Generated by Django 3.2.7 on 2022-07-14 00:34

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0059_alter_stylecontrol_font_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='body_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='body_font_family',
            field=models.CharField(blank=True, choices=[('FU', 'Futura'), ('GA', 'Garamond'), ('HE', 'Helvetica'), ('PA', 'Papyrus'), ('RO', 'Rockwell'), ('SO', 'Source Sans Pro'), ('TN', 'Times New Roman'), ('VE', 'Verdana')], default='SO', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='body_font_size',
            field=models.IntegerField(blank=True, choices=[(2, 2), (4, 4), (6, 6), (8, 8), (10, 10), (12, 12), (14, 14), (16, 16), (18, 18), (20, 20), (22, 22), (24, 24), (26, 26), (28, 28), (30, 30), (32, 32), (34, 34), (36, 36), (38, 38), (40, 40)], default=18, null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='image_heading_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='image_heading_font_family',
            field=models.CharField(blank=True, choices=[('FU', 'Futura'), ('GA', 'Garamond'), ('HE', 'Helvetica'), ('PA', 'Papyrus'), ('RO', 'Rockwell'), ('SO', 'Source Sans Pro'), ('TN', 'Times New Roman'), ('VE', 'Verdana')], default='SO', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='image_heading_font_size',
            field=models.IntegerField(blank=True, choices=[(2, 2), (4, 4), (6, 6), (8, 8), (10, 10), (12, 12), (14, 14), (16, 16), (18, 18), (20, 20), (22, 22), (24, 24), (26, 26), (28, 28), (30, 30), (32, 32), (34, 34), (36, 36), (38, 38), (40, 40)], default=18, null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='tagline_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='tagline_font_family',
            field=models.CharField(blank=True, choices=[('FU', 'Futura'), ('GA', 'Garamond'), ('HE', 'Helvetica'), ('PA', 'Papyrus'), ('RO', 'Rockwell'), ('SO', 'Source Sans Pro'), ('TN', 'Times New Roman'), ('VE', 'Verdana')], default='SO', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='tagline_font_size',
            field=models.IntegerField(blank=True, choices=[(2, 2), (4, 4), (6, 6), (8, 8), (10, 10), (12, 12), (14, 14), (16, 16), (18, 18), (20, 20), (22, 22), (24, 24), (26, 26), (28, 28), (30, 30), (32, 32), (34, 34), (36, 36), (38, 38), (40, 40)], default=18, null=True),
        ),
        migrations.AlterField(
            model_name='stylecontrol',
            name='background_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='stylecontrol',
            name='header_maintext_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='stylecontrol',
            name='header_smalltext_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
