# Generated by Django 3.2.7 on 2022-07-15 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0065_auto_20220715_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='body_opacity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
