# Generated by Django 3.2.7 on 2022-07-15 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0066_mainpage_body_opacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='body_opacity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Body opacity (max 100):'),
        ),
    ]
