# Generated by Django 3.2.7 on 2022-07-22 20:10

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0071_auto_20220721_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='content_byline_font_color',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='content_byline_font_family',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='content_byline_font_size',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='content_byline_opacity',
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='byline_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='byline color'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='byline_font_family',
            field=models.CharField(blank=True, choices=[('FU', 'Futura'), ('GA', 'Garamond'), ('HE', 'Helvetica'), ('PA', 'Papyrus'), ('RO', 'Rockwell'), ('SO', 'Source Sans Pro'), ('TN', 'Times New Roman'), ('VE', 'Verdana')], max_length=200, null=True, verbose_name='byline font'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='byline_font_size',
            field=models.IntegerField(blank=True, choices=[(2, 2), (4, 4), (6, 6), (8, 8), (10, 10), (12, 12), (14, 14), (16, 16), (18, 18), (20, 20), (22, 22), (24, 24), (26, 26), (28, 28), (30, 30), (32, 32), (34, 34), (36, 36), (38, 38), (40, 40)], null=True, verbose_name='byline size (px)'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='byline_opacity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='byline opacity (%)'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='body color'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_font_family',
            field=models.CharField(blank=True, choices=[('FU', 'Futura'), ('GA', 'Garamond'), ('HE', 'Helvetica'), ('PA', 'Papyrus'), ('RO', 'Rockwell'), ('SO', 'Source Sans Pro'), ('TN', 'Times New Roman'), ('VE', 'Verdana')], max_length=200, null=True, verbose_name='body font'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_font_size',
            field=models.IntegerField(blank=True, choices=[(2, 2), (4, 4), (6, 6), (8, 8), (10, 10), (12, 12), (14, 14), (16, 16), (18, 18), (20, 20), (22, 22), (24, 24), (26, 26), (28, 28), (30, 30), (32, 32), (34, 34), (36, 36), (38, 38), (40, 40)], null=True, verbose_name='body size (px)'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_opacity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='body opacity (%)'),
        ),
        migrations.AddField(
            model_name='post',
            name='byline_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='byline color'),
        ),
        migrations.AddField(
            model_name='post',
            name='byline_font_family',
            field=models.CharField(blank=True, choices=[('FU', 'Futura'), ('GA', 'Garamond'), ('HE', 'Helvetica'), ('PA', 'Papyrus'), ('RO', 'Rockwell'), ('SO', 'Source Sans Pro'), ('TN', 'Times New Roman'), ('VE', 'Verdana')], max_length=200, null=True, verbose_name='byline font'),
        ),
        migrations.AddField(
            model_name='post',
            name='byline_font_size',
            field=models.IntegerField(blank=True, choices=[(2, 2), (4, 4), (6, 6), (8, 8), (10, 10), (12, 12), (14, 14), (16, 16), (18, 18), (20, 20), (22, 22), (24, 24), (26, 26), (28, 28), (30, 30), (32, 32), (34, 34), (36, 36), (38, 38), (40, 40)], null=True, verbose_name='byline size (px)'),
        ),
        migrations.AddField(
            model_name='post',
            name='byline_opacity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='byline opacity (%)'),
        ),
        migrations.AddField(
            model_name='post',
            name='primary_heading_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='heading color'),
        ),
        migrations.AddField(
            model_name='post',
            name='primary_heading_font_family',
            field=models.CharField(blank=True, choices=[('FU', 'Futura'), ('GA', 'Garamond'), ('HE', 'Helvetica'), ('PA', 'Papyrus'), ('RO', 'Rockwell'), ('SO', 'Source Sans Pro'), ('TN', 'Times New Roman'), ('VE', 'Verdana')], max_length=200, null=True, verbose_name='heading font'),
        ),
        migrations.AddField(
            model_name='post',
            name='primary_heading_font_size',
            field=models.IntegerField(blank=True, choices=[(2, 2), (4, 4), (6, 6), (8, 8), (10, 10), (12, 12), (14, 14), (16, 16), (18, 18), (20, 20), (22, 22), (24, 24), (26, 26), (28, 28), (30, 30), (32, 32), (34, 34), (36, 36), (38, 38), (40, 40)], null=True, verbose_name='heading size (px)'),
        ),
        migrations.AddField(
            model_name='post',
            name='primary_heading_opacity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='heading opacity (%)'),
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='content_body_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='body color'),
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='content_body_font_family',
            field=models.CharField(blank=True, choices=[('FU', 'Futura'), ('GA', 'Garamond'), ('HE', 'Helvetica'), ('PA', 'Papyrus'), ('RO', 'Rockwell'), ('SO', 'Source Sans Pro'), ('TN', 'Times New Roman'), ('VE', 'Verdana')], max_length=200, null=True, verbose_name='body font'),
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='content_body_font_size',
            field=models.IntegerField(blank=True, choices=[(2, 2), (4, 4), (6, 6), (8, 8), (10, 10), (12, 12), (14, 14), (16, 16), (18, 18), (20, 20), (22, 22), (24, 24), (26, 26), (28, 28), (30, 30), (32, 32), (34, 34), (36, 36), (38, 38), (40, 40)], null=True, verbose_name='body size (px)'),
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='content_body_opacity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='body opacity (%)'),
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='content_heading_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='heading color'),
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='content_heading_font_family',
            field=models.CharField(blank=True, choices=[('FU', 'Futura'), ('GA', 'Garamond'), ('HE', 'Helvetica'), ('PA', 'Papyrus'), ('RO', 'Rockwell'), ('SO', 'Source Sans Pro'), ('TN', 'Times New Roman'), ('VE', 'Verdana')], max_length=200, null=True, verbose_name='heading font'),
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='content_heading_font_size',
            field=models.IntegerField(blank=True, choices=[(2, 2), (4, 4), (6, 6), (8, 8), (10, 10), (12, 12), (14, 14), (16, 16), (18, 18), (20, 20), (22, 22), (24, 24), (26, 26), (28, 28), (30, 30), (32, 32), (34, 34), (36, 36), (38, 38), (40, 40)], null=True, verbose_name='heading size (px)'),
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='content_heading_opacity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='heading opacity (%)'),
        ),
    ]
