# Generated by Django 3.2.7 on 2022-07-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0074_auto_20220727_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylesheet',
            name='parent',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
