# Generated by Django 3.2.7 on 2022-07-29 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0078_mainpage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='body_font_color',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='body_font_family',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='body_font_size',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='body_opacity',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image_heading_font_color',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image_heading_font_family',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image_heading_font_size',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image_heading_opacity',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='primary_heading_font_color',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='primary_heading_font_family',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='primary_heading_font_size',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='primary_heading_opacity',
        ),
    ]
