# Generated by Django 3.2.7 on 2022-07-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0079_auto_20220728_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylesheet',
            name='parent',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
