# Generated by Django 3.2.7 on 2022-07-29 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0080_alter_stylesheet_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body_font_color',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body_font_family',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body_font_size',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body_opacity',
        ),
        migrations.RemoveField(
            model_name='post',
            name='byline_font_color',
        ),
        migrations.RemoveField(
            model_name='post',
            name='byline_font_family',
        ),
        migrations.RemoveField(
            model_name='post',
            name='byline_font_size',
        ),
        migrations.RemoveField(
            model_name='post',
            name='byline_opacity',
        ),
        migrations.RemoveField(
            model_name='post',
            name='primary_heading_font_color',
        ),
        migrations.RemoveField(
            model_name='post',
            name='primary_heading_font_family',
        ),
        migrations.RemoveField(
            model_name='post',
            name='primary_heading_font_size',
        ),
        migrations.RemoveField(
            model_name='post',
            name='primary_heading_opacity',
        ),
        migrations.AddField(
            model_name='post',
            name='style_sheet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.stylesheet'),
        ),
    ]
