# Generated by Django 3.2.7 on 2022-07-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0082_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylesheet',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='stylesheet',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
