# Generated by Django 3.2.7 on 2022-07-30 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0085_auto_20220729_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministerialrecord',
            name='style_sheet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.stylesheet'),
        ),
        migrations.AddField(
            model_name='ministerialrecord',
            name='title',
            field=models.CharField(default='Ministerial Record', max_length=255),
        ),
    ]
