# Generated by Django 3.2.7 on 2022-07-30 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0086_auto_20220729_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='artandmusicpage',
            name='style_sheet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.stylesheet'),
        ),
        migrations.AddField(
            model_name='artandmusicpage',
            name='title',
            field=models.CharField(default='Art and Music Page', max_length=255),
        ),
    ]
