# Generated by Django 3.2.7 on 2022-07-30 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0087_auto_20220729_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacredjourney',
            name='style_sheet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.stylesheet'),
        ),
    ]
