# Generated by Django 3.2.7 on 2022-07-30 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0088_sacredjourney_style_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidedmeditationpage',
            name='style_sheet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.stylesheet'),
        ),
        migrations.AlterField(
            model_name='guidedmeditationpage',
            name='title',
            field=models.CharField(default='Guided Meditations', max_length=200),
        ),
    ]
