# Generated by Django 3.2.7 on 2022-07-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0089_auto_20220729_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidedmeditationpage',
            name='main_text',
            field=models.TextField(blank=True, null=True, verbose_name='blurb'),
        ),
    ]
