# Generated by Django 3.2.7 on 2022-07-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0091_galleryimage_style_sheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='font_size',
        ),
    ]
