# Generated by Django 3.2.7 on 2022-07-30 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0093_contactpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='byline_font_color',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='byline_font_family',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='byline_font_size',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='byline_opacity',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='content_body_font_color',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='content_body_font_family',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='content_body_font_size',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='content_body_opacity',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='content_heading_font_color',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='content_heading_font_family',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='content_heading_font_size',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='content_heading_opacity',
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='style_sheet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.stylesheet'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='title',
            field=models.CharField(default='Blog Index', max_length=200),
        ),
        migrations.AddField(
            model_name='sacredjourneypage',
            name='style_sheet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.stylesheet'),
        ),
        migrations.AddField(
            model_name='sacredjourneypage',
            name='title',
            field=models.CharField(default='Sacred Journey Index', max_length=200),
        ),
    ]
