# Generated by Django 3.2.7 on 2022-08-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0095_auto_20220730_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministerialrecord',
            name='blurb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ministerialrecord',
            name='video_caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ministerialrecord',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
