# Generated by Django 3.2.7 on 2022-08-15 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0096_auto_20220810_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MinistryPage',
        ),
        migrations.AlterField(
            model_name='stylecontrol',
            name='header_smalltext_opacity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='"by Rev. Wayne Walder opacity" (%)'),
        ),
    ]
