# Generated by Django 3.2.7 on 2022-08-18 03:52

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0099_auto_20220816_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylecontrol',
            name='font_weight',
        ),
        migrations.AddField(
            model_name='stylecontrol',
            name='footer_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='stylecontrol',
            name='footer_font_family',
            field=models.CharField(blank=True, choices=[('FU', 'Futura'), ('GA', 'Garamond'), ('HE', 'Helvetica'), ('PA', 'Papyrus'), ('RO', 'Rockwell'), ('SO', 'Source Sans Pro'), ('TN', 'Times New Roman'), ('VE', 'Verdana')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stylecontrol',
            name='footer_font_size',
            field=models.IntegerField(blank=True, choices=[(2, 2), (4, 4), (6, 6), (8, 8), (10, 10), (12, 12), (14, 14), (16, 16), (18, 18), (20, 20), (22, 22), (24, 24), (26, 26), (28, 28), (30, 30), (32, 32), (34, 34), (36, 36), (38, 38), (40, 40)], null=True),
        ),
        migrations.AddField(
            model_name='stylecontrol',
            name='footer_opacity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Opacity (%)'),
        ),
    ]
