# Generated by Django 3.2.7 on 2022-08-18 03:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0100_auto_20220817_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylecontrol',
            name='footer_opacity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Footer opacity (%)'),
        ),
    ]
