# Generated by Django 3.2.7 on 2022-08-19 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0102_auto_20220818_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylecontrol',
            name='background_opacity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Background opacity (%)'),
        ),
    ]
