# Generated by Django 3.2.7 on 2022-11-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0103_stylecontrol_background_opacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='audio_file_caption',
            field=models.TextField(blank=True, null=True, verbose_name='welcome message'),
        ),
    ]
