# Generated by Django 3.2.7 on 2022-12-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0108_alter_galleryimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacredjourneypage',
            name='upcoming_journeys_blurb',
            field=models.TextField(blank=True, null=True),
        ),
    ]
