# Generated by Django 3.2.7 on 2023-03-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0112_auto_20230315_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='blurb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
